#!/usr/bin/env bash

history_file="$HOME/.cache/dmenu-calc"
get_history() {
    [[ ! -f $history_file ]] && mkdir -p $(dirname $history_file) && touch $history_file
    [[ ! -s $history_file ]] && echo "No history found" || tac $history_file
}

is_in_history() { grep -q -x -F "$1" "$history_file"; }

add_to_history() { echo "$1" >>"$history_file"; }

copy_to_clipboard() { printf %s "$1" | wl-copy; }

result_from_equation() { printf %s "$1" | cut -d '=' -f 2; }
# result_from_equation() { printf %s "$1" | sed 's/^.*\(=\|≈\) //'; }

main() {
    dmenu_cmd="dmenu -l 10 -p"
    while
        input=$(get_history | ${dmenu_cmd} "Calculator: " "$@")
        [[ -n $input ]] # quit == no input
    do

        equation=$(qalc "$input")
        is_in_history "$input" || add_to_history "$equation"
        copy_to_clipboard "$(result_from_equation "$input")"
    done
}
main "$@"
